### ISSUE TITLE
Urllib quote on paths causes empty results for special chars

### ISSUE THREAD

**Issue by wejendorp** [muhuk/python-awis#11] opened 2015-03-17 11:02 UTC
Fails with 0 results:
```python
api = AwisApi(ACCESS_ID, SECRET_ACCESS_KEY)
tree = api.category_listings("Top/World/Dansk/Børn_og_unge")
listings = tree.findall('//awis:Listing', AwisApi.NS_PREFIXES)
print len(listings)  # 0
```

Works:
```python
api.request({
    'Action': 'CategoryListings',
    'ResponseGroup': 'Listings',
    'Descriptions': False,
    'Path': "Top/World/Dansk/Børn_og_unge",
    'Start': 1
})
listings = tree.findall('//awis:Listing', AwisApi.NS_PREFIXES)
print len(listings)  # 20
```

It must be caused by the quoting.

**Comment by muhuk** [comment] 2016-03-07 07:59
It seems [you are right](http://stackoverflow.com/a/5605354/42188).

`quote` seems to be doing some sort of UTF-8 escaping:

    >>> quote('Top/World/Dansk/Børn_og_unge')
    'Top/World/Dansk/B%C3%B8rn_og_unge'
    >>> print unquote('Top/World/Dansk/B%C3%B8rn_og_unge')
    Top/World/Dansk/Børn_og_unge

I think the problem is `'Path'` is being encoded twice:

    >>> urlencode({'Path': 'Top/World/Dansk/Børn_og_unge'})
    'Path=Top%2FWorld%2FDansk%2FB%C3%B8rn_og_unge'
    >>> urlencode({'Path': quote('Top/World/Dansk/Børn_og_unge')})
    'Path=Top%2FWorld%2FDansk%2FB%25C3%25B8rn_og_unge'

Sorry for the super delayed response.

**Comment by muhuk** [comment] 2016-04-20 06:54
@allenluce could you please take a look at this?

We do `urlencode` on the `params` before sending the request. Do we still need the `quote` [here](https://github.com/muhuk/python-awis/blob/8d59409074fab4529b9458a76a5a16ebec153b75/awis/__init__.py#L124)?

**Comment by muhuk** [comment] 2016-05-14 06:28
I contacted Amazon support to provide an account so that I can debug these things. I had closed my account some time ago and didn't want to give them my credit card. Basically what I was asking is to use the [free requests](https://aws.amazon.com/awis/) so that I can work (for free) on the Python connector for their product. They said "no".

I am going to stop supporting this library. Basically this happened because I merged a PR without personally verifying that it work. And now there is a bug, the original author doesn't respond and I don't have an AWS account to debug.

**Closed by muhuk** 2016-05-14 06:28 UTC

**Comment by allenluce** [comment] 2016-05-15 02:29
Sorry, somehow lost that initial email.  Yeah, removing that does the job.  If you're still going to give this one up, let me know. I'll be happy to grab it.

**Comment by muhuk** [comment] 2016-05-15 06:36
Hi @allenluce. Like I said above, I won't be able to personally confirm changes.

I would encourage you to fork the project. Please respect the license when doing so.

(Notifications get lost so easy, I'm beginning to wonder if GH has designed it in purpose. I wouldn't leave a ticket unanswered for 1 f#$%^ng year.)

**Comment by allenluce** [comment] 2016-05-15 06:53
@muhuk thanks. As long as the license doesn't prevent me from making changes that are useful to myself and others, I imagine that observance won't be an issue.

I think me missing the notification is an issue of too many emails. I don't think github is to blame in this case.

**Comment by allenluce** [comment] 2016-05-26 16:45
@muhuk how might I get an updated package in Pypi?

**Comment by muhuk** [comment] 2016-05-27 06:03
@allenluce when I said `fork` I didn't mean it in this sense:

![screenshot104](https://cloud.githubusercontent.com/assets/40178/15599043/cae51906-23e8-11e6-9a51-799d2dfc384e.png)

I meant a proper fork of the project. That's why I also said "please respect a license".

-----

In a nutshell:

1. Rename the project. Remove all mentions of `python-awis` but keep a mention that your code is based on it. Preferably with a link to the repo.
2. Replace the maintaier as yourself, remove the contributors.
3. Place your own license summary on top of the source files. But keep the original one as is.

Since you have renamed the project, now you can push your packages to PyPI.

If you'd like to discuss this further feel free to email me.
